name: Test TypeScript and Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/static-root-checks.yml'
      - 'package/src/**'
      - '*'
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: static-root-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Install package node dependencies
        working-directory: package
        run: yarn
      - name: Check types
        run: yarn ts-check
      - name: Lint
        run: yarn lint:js-package
